spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:carrinhocompras
    driver-class-name: org.h2.Driver
    username: sa
    password: 
      
springdoc:
  api-docs:
    path: /api-docs
